### ISSUE TITLE
php

### ISSUE THREAD

**Issue by Ezxibet** [imamrasyid/XBANPB-WebsiteV42#1]
hello, first of all sorry for my bad english.
Can you share the api(Hosts.php-delete.php-keygennX.php-add.php) files for dragon guard (anticheat). If I manage to get it running, I'll post it as open source on github.
-thanks XHX

**Comment by imamrasyid** [comment]
i dont have any source of dragon guard
but, if you want to collab, just create new repo, and i'll help you to fix

**Comment by Ezxibet** [comment]
github.com/Ezxibet/Guard-V1-NO-API
-please look :) :+1:

**Comment by Ezxibet** [comment]
please give discord address, i have launcher server updater to give you. We can share them by making their api.

**Comment by imamrasyid** [comment]
there many risk of modifying the program, i not recommend use that source
the program is trying to intimidate users pc's, that is ilegal action i guess.

but, you can contact me on discord Lolsecs#2192

**Comment by Ezxibet** [comment]
I can't reach you add me :)
HinataX#1310
